### ISSUE TITLE
select CMakeLists.txt when starting VS Code

### ISSUE THREAD

**Issue by Plitkam** [RoboGnome/VS_Code_ROS#6]
When VS Code in the root folder of my workspace, it asks me to select a CMakeLists.txt file. But if i understood correctly every ROS package in the workspace has such a file. If I disable the extension, than the prompt won't show up any more, but I loose the nice formation in the CMakeLists.txt files. I was wondering, whether you could help me about this, or eventually incorporate this in your guide. 
All help is greatly appreciated.

![image](https://github.com/lzptr/VS_Code_ROS/assets/34819813/74272ce8-783c-48dc-950d-9426d8207254)

**Comment by lzptr** [comment]
Hi @Plitkam,

just to clarify, your problem is wit the cmake tools extension from microsoft that asks for a cmake file to be used as the root cmake file?
I personally don't use the Cmake Tools extension from microsoft, because I get more flexibility out of my toolchain, if I just add a task.json with my needed build configuration.
There is another extension that only adds the language support for cmake files from twxs that I use and that gives you the intellisense and syntax highlighting support.:
![image](https://github.com/lzptr/VS_Code_ROS/assets/26966675/a03d5383-5650-4e20-b613-e5daaa59835c)


When building ROS nodes I used catkin_make anyway, but it's also been a while since I did somewthing with ROS :)

**Comment by Plitkam** [comment]
Yes you understand my problem correctly. Nice, thank you very much for your answer. I installed the one you recommended and I do not get the unwanted notification any more. Actually I use ROS2 but your tutorial is still a very good collection of preparations for a new workspace. :D
